package com.helpinghands.domain.entity;

public enum NotificationType {
    VERIFICATION_APPROVED,
    VERIFICATION_REJECTED,
    REQUEST_PLEDGED,
    REQUEST_ACCEPTED,
    REQUEST_DELIVERED,
    REQUEST_COMPLETED,
    REQUEST_CANCELLED,
    RATING_RECEIVED,
    ACCOUNT_SUSPENDED,
    ACCOUNT_REINSTATED,
    CONTENT_FLAGGED
}
